name: Deploy Yii2 App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Run Ansible Playbook
      run: |
        sudo apt update
        sudo apt install -y ansible
        ansible-playbook -i inventory.ini playbook.yml
